### ISSUE TITLE
Translate "The Githubification of InfoSec" article to Russian

### ISSUE THREAD

**Issue by yugoslavskiy** [JohnLaTwC/Shared#2]
Here is the [google document](https://docs.google.com/document/d/1x-kt35c7_2fOj5Y2wvPHaHeQ7Om5FrS3_lchj0uZBDg/edit) that we use for collaborative translation.

Ping me here on GitHub or in [Telegram](https://t.me/yugoslavskiy) for edit access to the doc if you would like to join the translation.

The initial translation has been provided by Sergei Korneev. 

After finishing the translation of the text, we will create `Presentations/The Githubification of InfoSec_RU.md` file in Markdown format with proper images and formatting.

After that, the article will be published on [habr.com](https://habr.com/ru/top/).

## Tips

- ~~Use [grammarly](https://app.grammarly.com/). It helps a lot~~ — actually it helps with translation TO English (: 
- No need to worry about splitting parts of the documents between contributors, google docs is sort of WYSIWYG editor that provides us with the ability to work on it online all together

**Comment by ashed** [comment]
[The Githubification of InfoSec-ru.zip](https://github.com/JohnLaTwC/Shared/files/4044475/The.Githubification.of.InfoSec-ru.zip)

First draft Russian translation

**Comment by yugoslavskiy** [comment]
Hello @ashed ! Could you please sync your translation with the [google document](https://docs.google.com/document/d/1x-kt35c7_2fOj5Y2wvPHaHeQ7Om5FrS3_lchj0uZBDg/edit)?

**Comment by mazahaka-jay** [comment]
Reverso context also helps a lot.
